# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI/CD with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Build with Maven
        run: mvn -B package --file pom.xml

        # Runs a single command using the runners shell
      - name: Jenkinsfile Runner Prepackaged
        run: jenkinsci/jenkinsfile-runner-github-actions@v0.2

        # Runs a single command using the runners shell
      - name: Build Dockerfile jenkinsfile-runner
        run: docker build -t jenkinsfile-runner .

        # Runs a single command using the runners shell
      - name: Build Dockerfile jenkinsfile-runner-lazyload
        run: docker build -f jenkinsfile-runner-lazyloaded/Dockerfile -t jenkinsfile-runner-lazyload .

        # Runs a set of commands using the runners shell
      - name: Build Dockerfile jenkinsfile-runner-prepackaged
        run: docker build -f jenkinsfile-runner-prepackaged/Dockerfile -t jenkinsfile-runner-prepackaged .


        #Docker build
      - name: Build and push Docker images
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: sharifgab/app
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Jenkins single-shot master

      - uses: actions/checkout@master
      - name: jenkinsfile-runner-prepackaged
        uses: jenkinsci/jenkinsfile-runner-github-actions/jenkinsfile-runner-prepackaged@master
        env:
          GITHUB_TOKEN: ${{ secrets.user }}
